version: "3"

services:
  app:
    build: ./app
    container_name: app
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Z1qYALrscGdNYUMJDuqS
      MYSQL_DATABASE: nextjs_db
    depends_on:
      - mysql
    command: sh -c './wait-for-it.sh mysql:3306 -- npm start'

  mysql:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Z1qYALrscGdNYUMJDuqS
      MYSQL_DATABASE: nextjs_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: