version: "3"

services:
  app:
    build: ./app
    container_name: app
    restart: always
    volumes:
      - /app:/app
    ports:
      - "80:3000"
  mysql:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Z1qYALrscGdNYUMJDuqS
    ports:
    - '3306:3306'
    volumes:
      - ./db/hydropi.sql:/docker-entrypoint-inidb.d/hydropi.sql