version: "3"

services:
  #app:
  #  build: ./app
  #  container_name: app
  #  restart: always
  #  volumes:
  #    - /app:/app
  #  ports:
  #    - "80:3000"
  mysql:
    build: ./db
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Z1qYALrscGdNYUMJDuqS
    ports:
    - '3306:3306'
    volumes:
      - ./db:/docker-entrypoint-inidb.d